import Image from "next/image";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { getMarket,isMarketKey,marketRoutes } from "@/data/markets";
import { getResource,resourcesForMarket } from "@/data/resources";
import styles from "../../../service.module.css";
export function generateStaticParams(){return ["az","tx"].flatMap(m=>resourcesForMarket(m as "az"|"tx").map(a=>({market:m,slug:a.slug})))}
export async function generateMetadata({params}:{params:Promise<{market:string;slug:string}>}):Promise<Metadata>{const{market,slug}=await params;if(!isMarketKey(market))return{};const a=getResource(market,slug);if(!a)return{};return{title:a.title,description:a.description,alternates:{canonical:`/${market}/resources/${slug}`},openGraph:{type:"article",title:a.title,description:a.description,url:`/${market}/resources/${slug}`,images:[{url:a.image,width:640,height:440,alt:a.imageAlt}]}}}
export default async function Page({params}:{params:Promise<{market:string;slug:string}>}){const{market,slug}=await params;if(!isMarketKey(market))notFound();const cfg=getMarket(market)!;const r=marketRoutes(market);const a=getResource(market,slug);if(!a)notFound();const schema={"@context":"https://schema.org","@type":"Article",headline:a.title,description:a.description,datePublished:a.published,dateModified:a.updated,author:{"@type":"Organization",name:`${cfg.brandShort} — ${cfg.brandName}`},publisher:{"@type":"Organization",name:`${cfg.brandShort} — ${cfg.brandName}`},mainEntityOfPage:`https://electronicrecycle.net/${market}/resources/${slug}`};return <article className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className={styles.hero}><div className={`ever-shell ${styles.heroGrid}`}><div><Breadcrumbs items={[{label:"Home",href:r.home},{label:"Resources",href:r.resources},{label:a.title}]}/><p className="ever-eyebrow">{a.primaryKeyword}</p><h1>{a.title}</h1><p>{a.intro}</p></div><div className={styles.heroVisual}><Image src={a.image} alt={a.imageAlt} width={640} height={440} priority/></div></div></section><section className={styles.body}><div className="ever-shell"><div className={styles.contentGrid}><div className={styles.mainContent}>{a.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2><p>{s.body}</p></section>)}<section><h2>Next step</h2><p>Check the current item policy before relying on an older search result or saved article. Local pickup details are confirmed before scheduling.</p><div className={styles.heroActions}><Link href={r.residential}>Check an item</Link>{a.citySlug?<Link href={`/${market}/${a.citySlug}`}>Local {cfg.stateAbbr} page</Link>:null}{a.serviceSlug?<Link href={`/${market}/services/${a.serviceSlug}`}>Related service</Link>:null}</div></section></div></div></div></section></article>}
