import Image from "next/image";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { getMarket, isMarketKey, marketRoutes } from "@/data/markets";
import { getSeoService, getMarketSeoServices } from "@/data/seo-services";
import { publishableCities } from "@/data/service-areas";
import styles from "../../../service.module.css";

export function generateStaticParams(){return ["az","tx"].flatMap(market=>getMarketSeoServices(market as "az"|"tx").map(service=>({market,service:service.slug})))}
export async function generateMetadata({params}:{params:Promise<{market:string;service:string}>}):Promise<Metadata>{const{market,service:slug}=await params;if(!isMarketKey(market))return{};const service=getSeoService(market,slug);if(!service)return{};return{title:service.title,description:service.description,alternates:{canonical:`/${market}/services/${service.slug}`},openGraph:{title:service.title,description:service.description,url:`/${market}/services/${service.slug}`,images:[{url:"/brand/ever-og.png",width:1200,height:630,alt:service.imageAlt}]}}}
export default async function ServicePage({params}:{params:Promise<{market:string;service:string}>}){const{market,service:slug}=await params;if(!isMarketKey(market))notFound();const cfg=getMarket(market)!;const routes=marketRoutes(market);const service=getSeoService(market,slug);if(!service)notFound();const related=service.related.map(s=>getSeoService(market,s)).filter(Boolean) as NonNullable<ReturnType<typeof getSeoService>>[];const cities=publishableCities(market);const schema={"@context":"https://schema.org","@type":"Service",name:service.h1,description:service.description,provider:{"@type":"Organization",name:`${cfg.brandShort} — ${cfg.brandName}`,url:`https://electronicrecycle.net/${market}`},areaServed:cities.map(c=>({"@type":"City",name:`${c.name}, ${cfg.state}`})),url:`https://electronicrecycle.net/${market}/services/${service.slug}`};return <div className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className={styles.hero}><div className={`ever-shell ${styles.heroGrid}`}><div><Breadcrumbs items={[{label:"Home",href:routes.home},{label:"Services",href:routes.services},{label:service.h1}]}/><h1>{service.h1}</h1><p>{service.intro}</p><div className={styles.heroActions}><Link href={routes.residential}>Check an item</Link><Link href={routes.business}>Plan a business pickup</Link></div></div><div className={styles.heroVisual}><Image src={service.image} alt={service.imageAlt} width={640} height={440} priority/></div></div></section><section className={styles.body}><div className="ever-shell"><ul className={styles.bullets}>{service.bullets.map(b=><li key={b}>{b}</li>)}</ul><div className={styles.contentGrid}><div className={styles.mainContent}>{service.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2><p>{s.body}</p></section>)}<section><h2>Service areas</h2><p>{cfg.brandShort} serves {cfg.serviceAreaSummary}. Pickup availability and pricing depend on the load, item type, and location.</p><div className={styles.cityLinks}>{cities.map(c=><Link key={c.slug} href={`/${market}/${c.slug}`}>{c.name}</Link>)}</div></section><section><h2>Frequently asked questions</h2><div className={styles.faqList}>{service.faqs.map(i=><details key={i.question}><summary>{i.question}</summary><p>{i.answer}</p></details>)}</div></section></div><aside className={styles.sidebar}><h2>Related services</h2><ul>{related.map(i=><li key={i.slug}><Link href={`/${market}/services/${i.slug}`}>{i.h1}</Link></li>)}</ul><div className={styles.contactCard}><strong>Questions?</strong>{cfg.phone?<a href={`tel:${cfg.phone}`}>{cfg.phone}</a>:null}{cfg.email?<a href={`mailto:${cfg.email}`}>{cfg.email}</a>:<Link href={routes.contact}>Contact {cfg.brandShort}</Link>}</div></aside></div></div></section></div>}
